[package]
name = "audioboiler_traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"

[dev-dependencies]
audioboiler_buffers = { path = "../audioboiler_buffers" }
